name: Sandbox
on:
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1.23.0
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: "14.3"
      - uses: actions/checkout@v3
      - name: Build
        run: exec ./.github/build.sh
      - name: Test
        run: exec ./.github/test.sh
